//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::NavMeshPlus.Components.NavMeshModifierTilemap.TileModifier))]
	public class PropertyProvider_NavMeshPlus_Components_NavMeshModifierTilemap_TileModifier : Unity.VisualScripting.SerializedPropertyProvider<NavMeshPlus.Components.NavMeshModifierTilemap.TileModifier>
	{
	}
}
